name: Code Style

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/lint.yml"
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/lint.yml"
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  test:
    name: Lints on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: cargo fmt
        run: cargo fmt --check

      - name: cargo clippy
        run: cargo clippy --tests --workspace -- -D warnings
